functions:
  process-file:
    handler: functions/process-file/handler.func
    role: ${self:custom.functionRoleArn}
    package:
      individually: true
      exclude:
      - ./**
      include:
      - functions/process-file/**