functions:
  process-file:
    handler: functions/process-file/handler.func
    role: ${self:custom.functionRoleArn}
    environment:
      TABLE_NAME: my-notes-${opt:stage}
    events:
      - s3: 
          bucket: ${self:custom.myNotesAttachmentBucketName}
          event: s3:ObjectCreated:Put
          existing: true
    package:
      individually: true
      patterns:
      - '!./**'
      - functions/process-file/**