functions:
  delete-note:
    memorySize: 128
    handler: functions/delete-note/handler.func
    role: ${self:custom.functionRoleArn}
    environment:
      TABLE_NAME: my-notes-${opt:stage}
      BUCKET_NAME: my-notes-${opt:stage}
    events:
      - http: 
          path: notes/{id}
          method: delete
          cors: true
          authorizer:
            name: my-notes-authorizer-${opt:stage}
            arn: ${self:custom.cognitoUserPoolArn}
    package:
      individually: true
      exclude:
      - ./**
      include:
      - functions/delete-note/**