functions:
  delete-note:
    memorySize: 128
    handler: functions/delete-note/handler.func
    role: ${self:custom.functionRoleArn}
    package:
      individually: true
      exclude:
      - ./**
      include:
      - functions/delete-note/**