functions:
  create-note:
    handler: functions/create-note/handler.func
    memorySize: 128
    role: arn:aws:iam::093271654888:role/my-notes-role-radek
    environment:
      TABLE_NAME: my-notes-${opt:stage}
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer:
            name: my-notes-authorizer-${opt:stage}
            arn: arn:aws:cognito-idp:eu-west-1:093271654888:userpool/eu-west-1_Zx7fjYW46
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer:
            name: my-notes-authorizer-${opt:stage}
            arn: arn:aws:cognito-idp:eu-west-1:093271654888:userpool/eu-west-1_Zx7fjYW46
    package:
      individually: true
      exclude:
      - ./**
      include:
      - functions/create-note/**