functions:
  create-note:
    handler: functions/create-note/handler.func
    memorySize: 128
    role: ${self:custom.functionRoleArn}
    package:
      individually: true
      patterns:
      - '!./**'
      - functions/create-note/**