functions:
  file-upload:
    handler: functions/file-upload/handler.func
    role: ${self:custom.functionRoleArn}
    package:
      individually: true
      patterns:
      - '!./**'
      - functions/file-upload/**