functions:
  file-upload:
    handler: functions/file-upload/handler.func
    role: arn:aws:iam::093271654888:role/my-notes-role-radek
    environment:
      TABLE_NAME: my-notes-${opt:stage}
      BUCKET_NAME: my-notes-${opt:stage}
    events:
      - http:
          path: notes/files/{id}
          method: get
          cors: true
          authorizer:
            name: my-notes-authorizer-${opt:stage}
            arn: arn:aws:cognito-idp:eu-west-1:093271654888:userpool/eu-west-1_Zx7fjYW46
      - http:
          path: notes/files
          method: post
          cors: true
          authorizer:
            name: my-notes-authorizer-${opt:stage}
            arn: arn:aws:cognito-idp:eu-west-1:093271654888:userpool/eu-west-1_Zx7fjYW46
    package:
      individually: true
      exclude:
      - ./**
      include:
      - functions/file-upload/**
