functions:
  file-upload:
    handler: functions/file-upload/handler.func
    role: ${self:custom.functionRoleArn}
    environment:
      BUCKET_NAME: my-notes-attachments-${opt:stage}
    events:
    - http:
        path: notes/files
        method: post
        cors: true
        authorizer:
          name: my-notes-authorizer-${opt:stage}
          arn: ${self:custom.cognitoUserPoolArn}
    package:
      individually: true
      exclude:
      - ./**
      include:
      - functions/file-upload/**
