functions:
  list-notes:
    handler: functions/list-notes/handler.func
    role: ${self:custom.functionRoleArn}
    package:
      individually: true
      exclude:
      - ./**
      include:
      - functions/list-notes/**