service: my-notes

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  - ${file(functions/create-note/serverless.yml):functions}
  - ${file(functions/delete-note/serverless.yml):functions}
  - ${file(functions/file-upload/serverless.yml):functions}
  - ${file(functions/list-notes/serverless.yml):functions}
  - ${file(functions/process-file/serverless.yml):functions}

resources:
  Resources:
    MyNotesTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: my-notes-${opt:stage}
        AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1