service: my-notes
frameworkVersion: '3'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

custom:
  functionRoleArn: TODO
  cognitoUserPoolArn: TODO
  myNotesAttachmentBucketName: my-notes-attachments-${opt:stage}

functions:
#  - ${file(functions/create-note/serverless.yml):functions}
#  - ${file(functions/delete-note/serverless.yml):functions}
#  - ${file(functions/file-upload/serverless.yml):functions}
#  - ${file(functions/list-notes/serverless.yml):functions}
#  - ${file(functions/process-file/serverless.yml):functions}